export function getMockData() {
 return [
  {
   groupId: "6ipopqou5o2v1",
   groupIdx: 3,
   views: [
    {
     columnId: "additionInfo1",
     groupId: "6ipopqou5o2v1",
     id: "1ib6b9b9ys9v3",
     operator: "=",
     readOnly: false,
     excludeOperators: ["hasTag"],
     filterType: "multipleLines",
     realIdx: 1,
    },
    {
     columnId: "additionInfo2",
     groupId: "6ipopqou5o2v1",
     id: "3vzrzfrtqomtj",
     operator: "=",
     readOnly: false,
     excludeOperators: ["hasTag"],
     filterType: "multipleLines",
     realIdx: 2,
    },
    {
     columnId: "tzpjytq4nfy4f3",
     groupId: "6ipopqou5o2v1",
     id: "f1uvuo1vt18vn",
     operator: "=",
     readOnly: false,
     excludeOperators: [],
     filterType: "language",
     realIdx: 3,
    },
   ],
   disabled: false,
   hasGroupId: true,
   status: "enabled",
  },
  {
   groupId: "pmytyjnszz5pl",
   groupIdx: 1,
   views: [
    {
     columnId: "_publicRecordId",
     id: "pmytyjnszz5pl",
     groupId: "",
     operator: "=",
     readOnly: false,
     excludeOperators: ["hasTag"],
     filterType: "_publicRecordId",
     realIdx: 0,
    },
   ],
   disabled: false,
   hasGroupId: false,
  },

  {
   groupId: "y3imijjsv4jo4",
   groupIdx: 5,
   views: [
    {
     columnId: "additionInfo4",
     groupId: "y3imijjsv4jo4",
     id: "1ib6b999trs69",
     operator: "=",
     readOnly: false,
     excludeOperators: ["hasTag"],
     filterType: "multipleLines",
     realIdx: 4,
    },
    {
     columnId: "tzpjytq4nfy4f3",
     groupId: "y3imijjsv4jo4",
     id: "7qipill27q49q",
     operator: "=",
     readOnly: false,
     excludeOperators: [],
     filterType: "language",
     realIdx: 5,
    },
   ],
   disabled: false,
   hasGroupId: true,
   status: "enabled",
  },
 ];
}
